### ISSUE TITLE
PaperSpigot上释放魔法阵导致错误

### ISSUE THREAD

**Issue by HeartyYF** [aegistudio/MagickElement#3]
在PaperSpigot-Build682上释放法阵（插件自带的）没有任何效果，同时控制台连环报错。
MagickElement] Task #57 for MagickElement v0.11-beta generated an exception
java.lang.NullPointerException
    at net.aegistudio.magick.seal.SparseGenerator.generate(SparseGenerator.java:17) ~[?:?]
    at net.aegistudio.magick.seal.MagickSealPaintTask.run(MagickSealPaintTask.java:25) ~[?:?]
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.9.2.jar:git-Paper-682]
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:721) [patched_1.9.2.jar:git-Paper-682]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:620) [patched_1.9.2.jar:git-Paper-682]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
相同错误连续报了近千遍。
另外为何MP上限无论如何不会增加？

**Comment by aegistudio** [comment]
你好：
1. 本插件<b>没有</b>任何一个发行版或子版本有自带的魔法阵效果
2. 请尝试当前主干版本（http://pan.baidu.com/s/1eS2kvrO ），测试前请删除plugins/MagickElement下<b>所有</b>文件。
3. MP与玩家当前最高等级相关。
谢谢。

Hey folks,
1. <b>none</b> release or subversion of this plugin has a default magick seal effect!
2. please try head version. (http://pan.baidu.com/s/1eS2kvrO ). Remove <b>any</b> file under the plugins/MagickElement before testing.
3. MP limit is correlated with player's current level.
Best regards.
